#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v3
# autospec commit: 750e50d
#
Name     : perl-Test-Future-IO-Impl
Version  : 0.14
Release  : 4
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Test-Future-IO-Impl-0.14.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Test-Future-IO-Impl-0.14.tar.gz
Summary  : 'acceptance tests for C<Future::IO> implementations'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-Future-IO-Impl-license = %{version}-%{release}
Requires: perl-Test-Future-IO-Impl-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Test::Future::IO::Impl - acceptance tests for Future::IO
implementations
SYNOPSIS

%package dev
Summary: dev components for the perl-Test-Future-IO-Impl package.
Group: Development
Provides: perl-Test-Future-IO-Impl-devel = %{version}-%{release}
Requires: perl-Test-Future-IO-Impl = %{version}-%{release}

%description dev
dev components for the perl-Test-Future-IO-Impl package.


%package license
Summary: license components for the perl-Test-Future-IO-Impl package.
Group: Default

%description license
license components for the perl-Test-Future-IO-Impl package.


%package perl
Summary: perl components for the perl-Test-Future-IO-Impl package.
Group: Default
Requires: perl-Test-Future-IO-Impl = %{version}-%{release}

%description perl
perl components for the perl-Test-Future-IO-Impl package.


%prep
%setup -q -n Test-Future-IO-Impl-0.14
cd %{_builddir}/Test-Future-IO-Impl-0.14
pushd ..
cp -a Test-Future-IO-Impl-0.14 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-Future-IO-Impl
cp %{_builddir}/Test-Future-IO-Impl-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-Future-IO-Impl/df9f2d29a10846c30925e18b0273e53356f88a79 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::Future::IO::Impl.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-Future-IO-Impl/df9f2d29a10846c30925e18b0273e53356f88a79

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
